import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "./components/Sidebar";
// import Navbar from "@/app/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashbaordLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        <main className="grid grid-cols-12">
          <div className="col-span-4 h-screen bg-[#212121]">
            <Sidebar />
          </div>
          <div className="col-span-8 h-screen bg-black border border-white">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
