import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import toast, { Toaster } from "react-hot-toast";
import { AuthContextProvider } from "@/Provider/AuthContextProvider";

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
    >
      <body>
        <Navbar />
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
      <Toaster />
    </html>
  );
}
