import { Inter } from "next/font/google";
import "../../globals.css";
import toast, { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import { SidebarDemo } from "@/components/SidebarDemo";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="antialiased">
        <Navbar></Navbar>
        <main className="pt-3">
          <SidebarDemo>{children}</SidebarDemo>
        </main>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
